### ISSUE TITLE
Error: CannotUploadAPK /home/vsts/work/r1/a/_fsEliteConnect-Mobile/fsElite Connect/app-release-signed.apk { Error: Cannot update a published APK.

### ISSUE THREAD

**Issue by AGhosh123** [microsoft/google-play-vsts-extension#310] opened 2021-10-27 14:31 UTC
HI Team,

Not able to upload apk to internal testing using Visual Studio Team Services Extension for Google Play.

![image](https://user-images.githubusercontent.com/59682376/139086506-d21544dd-7f95-4c23-b471-343a8d8703e7.png)

Please suggest.

**Comment by anatolybolshakov** [comment] 2021-11-01 11:12
@AGhosh123 thanks! As I see error comes from google api side - this error usually means that the versionCode specified in the app manifest is the same as version code of the already published apk - please make sure that there is no collisions.

**Comment by AGhosh123** [comment] 2021-11-03 07:24
@anatolybolshakov  I am doing versioning using below task.

- task: android-manifest-version@1
    displayName: 'versioning'
    inputs:
      sourcePath: '$(Build.SourcesDirectory)/platforms/android/app/src/main/AndroidManifest.xml'
      versionCodeOption: 'buildid'
      versionCode: '$(Build.BuildNumber)'
      versionCodeOffset: '0'
      versionName: 
      printFile: true

Still getting error while updating apk. Am I missing something?

**Comment by anatolybolshakov** [comment] 2021-11-08 15:41
@AGhosh123 android-manifest-version is external task for DevOps - please make sure that it updates version code properly, and there is no collision between specified version code, and version codes of already uploaded apk files.

**Comment by anatolybolshakov** [comment] 2021-11-30 18:12
@AGhosh123 could you please provide some minimal steps to reproduce the issue? I can't reproduce the issue at the moment.

**Comment by AGhosh123** [comment] 2021-12-03 11:59
@anatolybolshakov Below are the steps.
1. Versioning 
- task: android-manifest-version@1
    displayName: 'versioning'
    inputs:
      sourcePath: '$(Build.SourcesDirectory)/platforms/android/app/src/main/AndroidManifest.xml'
      versionCodeOption: 'buildid'
      versionCode: '$(Build.BuildNumber)'
      versionCodeOffset: '0'
      versionName: 
      printFile: true
2. Build
3. Deploy to internal testing 
steps:
- task: ms-vsclient.google-play.google-play-release.GooglePlayRelease@4
  displayName: 'Release fmPilot-Mobile to Internal test'
  inputs:
    serviceConnection: 'fmpilot-mobile-google-play'
    applicationId: com.ionicframework.mofam810753
    action: SingleApk
    apkFile: '$(System.DefaultWorkingDirectory)/_fmPilot-Mobile/fmPilot-Mobile/app-release-signed.apk'

**Comment by AGhosh123** [comment] 2021-12-16 06:50
@anatolybolshakov Did you get a chance to look into this?

**Comment by anatolybolshakov** [comment] 2021-12-16 14:40
Hi @AGhosh123 sorry for the delay - I still can not reproduce issue with these steps. In my pipeline android-manifest-version@1 task from [extension](https://marketplace.visualstudio.com/items?itemName=vs-publisher-473885.motz-mobile-buildtasks) updates app manifest properly, and app is being published to google play without errors - if there is no apk files already published to google play and there is no conflict in versions.

**Comment by anatolybolshakov** [comment] 2021-12-27 18:19
@AGhosh123 closing this as not reproducible at the moment. Please make sure that there is no collision between version code specified in manifest by android-manifest-version task and already uploaded applications.
Feel free to ask any other questions or share the steps which we could use to reproduce the issue on our side.

**Closed by anatolybolshakov** 2021-12-27 18:19 UTC
Labels: bug, Area: GooglePlay
