### ISSUE TITLE
Specify version with Promote Task

### ISSUE THREAD

**Issue by Noglen** [microsoft/google-play-vsts-extension#93] opened 2018-04-13 05:07 UTC
When using the Promote Task, it would be useful to specify which version in a track you want to promote.

eg. 
I publish V2 to the Alpha track, which is then tested.
I then publish V3 to the Aplha track with some new features.

Later, I then want to promote V2 to the Beta track.

Currently it works if I promote Alpha to Beta before publishing the new build to the Alpha track, but there are often times when I need to do this out of order (eg. if V1 was still being tested in the Beta track)

**Comment by deepamhatre** [comment] 2020-04-01 06:48
@Noglen I have created a stage 'Google Play - Release Bundle' to release my bundle to alpha track. Which is running fine. Then I created a new stage to promote this alpha track to beta using 'Google Play -Promote'.
This is promoting my bundle which I released in the first stage to beta track fine, but at the same time it is creating a new alpha track with the release name set to current date and this track doesn't show any apk added inside that. Could you please help me out on this. I am struggling with this from many days.

**Comment by kkalisz** [comment] 2021-01-29 18:23
Do you have any plans to work on that ?
Our use case is that we have release pipeline that releases apk to internal track,  after some tests we manually trigger stage that promotes app to production. (Everything is done in single release pipeline)

The problem is that we never can 100% sure what version is promoted.

In practice the is no problem, but to be SOC 2 compliant we need to be 100% sure that version promoted to production is the same version that was uploaded to store during this release.

The best solution would be giving possibility to set version code of apk that should be promoted to other track.
So in that case we will be 100% sure that versions matches.
Even if there is no plan for adding this in near future I need to know that :)

Best Regards

**Comment by anatolybolshakov** [comment] 2021-01-31 17:38
Hi @Noglen @deepamhatre @kkalisz would it work for you if there will be some input like 'Release name' - which would allow to filter and select which release to promote?

**Comment by kkalisz** [comment] 2021-02-01 16:44
Hi @anatolybolshakov 

Depending of implementation it should work.
But I'm not sure if we can provide some reliable filer/search functionality as in most cases during creation of pipeline definition we don't have any informations about future versions.

From my perspective these are 3 key points that are needed ( at least in my use case):
I would like to have optional "Release name" field where I can specify version code of apk that should be promoted.
I would like to have possibility to use pipeline/environment variable to specify version code to promote. 
I would expect to see job failure if apk with given version code is not present on source track.

**Comment by anatolybolshakov** [comment] 2021-05-19 17:07
Hi everyone, we rolled out fix for this issue - I'm closing this at the moment, please let us know if you have any other questions.

**Closed** 2021-05-19 17:08 UTC
Labels: Task: GPlay Promote, enhancement
