### ISSUE TITLE
Unable to Install Plugin

### ISSUE THREAD

**Issue by josephchrisman** [microsoft/google-play-vsts-extension#362] opened 2022-11-07 14:53 UTC
`Task definition input 'rolloutToUserFraction' and Task definition input 'isDraftRelease' must belong to same group as they are dependent inputs for Task with ID '8cf7cac0-620b-11e5-b4cf-8565e60f4d27'.`

![Screen Shot 2022-11-07 at 6 50 37 AM](https://user-images.githubusercontent.com/321362/200339927-f3082fcf-17f4-4361-a38f-8fbebc4e8951.png)

Steps:
1. From the corporate Azure Instance, searched for Google Play in the Marketplace
2. Click `Get it Free` from [this URL](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play)
3. Received the above error

**Comment by DmitriiBobreshev** [comment] 2022-11-08 08:25
Hi @josephchrisman, thanks for reporting, it seems like we already have a similar issue in [AppStore extension](https://github.com/microsoft/app-store-vsts-extension/issues/195) and a problem in a [commit though](https://github.com/microsoft/google-play-vsts-extension/commit/18936df8d9dd60c6d6e4e6faf027f2d6278cc85c#diff-07d01b0f000ffe7b9c1aad8aa457509c30a3bd8cfde6589580e0383b87f5f4fc). Anyway, thank again! We will take a look as fast as we could.

**Comment by ismayilov-ismayil** [comment] 2022-11-21 07:28
Hi @josephchrisman, thank you for bug reporting. 
I was not able to reproduce issue on my side. Please, help me to do this by answering questions:

1. Are you using on-prem Azure devops/TFS or cloud?
2. What is the version of Azure devops/TFS? You can check by this link [https://dev.azure.com/YOUR-organization/_home/About](https://dev.azure.com/your-organization/_home/About)
3. Did you try to manual installation? you can use this [link ](http://www.donovanbrown.com/post/how-do-i-upload-a-custom-task-for-build)

**Comment by w1ggor** [comment] 2022-11-24 16:48
Same thing happened with me 

![image](https://user-images.githubusercontent.com/69217585/203834297-e8a5e90b-9745-443b-b23c-36125a7883a9.png)

I am using TFS 2018 Update 3 on-premise

**Comment by w1ggor** [comment] 2022-11-25 12:55
![image](https://user-images.githubusercontent.com/69217585/203990176-ee3bf365-49d2-4444-9bba-657bfc775a86.png)
While trying to manual installing I got the same error while uploading the Release Task

**Comment by ismayilov-ismayil** [comment] 2022-11-27 19:55
Hi @w1ggor, thanks for your feedback. 
I will check and revert back soon

**Comment by ismayilov-ismayil** [comment] 2022-12-12 22:19
Hi @josephchrisman and @w1ggor 

My suggestion is to remove group name from dependent field in Tasks\GooglePlayReleaseV4\task[.loc].json as shown in screenshot then upload custom task to the server  - [guide](http://www.donovanbrown.com/post/how-do-i-upload-a-custom-task-for-build)

<img width="740" alt="image" src="https://user-images.githubusercontent.com/110806089/207167100-4d3ad2da-a1d0-43f9-b245-d00b2919ce1d.png">

BTW, TFS2018 has EOL support in few weeks, thus, please upgrade it to latest versions of AzureDevops

**Comment by ismayilov-ismayil** [comment] 2022-12-19 08:05
Hi @josephchrisman 
closing this ticket, feel free to ask any other questions or let us know if it's still relevant for you.

**Closed by ismayilov-ismayil** 2022-12-19 08:05 UTC
Labels: bug, Area: GooglePlay
