### ISSUE TITLE
Issue: Error: We have failed to run 'bundletool build-apks' on this Android App Bundle. Please ensure your bundle is valid by running 'bundletool build-apks' locally and try again. Error message output: File 'BundleConfig.pb' was not found..

### ISSUE THREAD

**Issue by VaniaOPereira** [microsoft/google-play-vsts-extension#315] opened 2021-11-16 14:37 UTC
I have this issue:
##[error]Error: Failed to upload the bundle /Users/runner/work/r1/a/XPTO.aab. Failed with message: Error: We have failed to run 'bundletool build-apks' on this Android App Bundle. Please ensure your bundle is valid by running 'bundletool build-apks' locally and try again. Error message output: File 'BundleConfig.pb' was not found..

**Comment by tatyana-kostromskaya** [comment] 2021-11-16 15:03
Hi @VaniaOPereira which task version do you use? Did it work before?

**Comment by VaniaOPereira** [comment] 2021-11-16 15:29
hi tatyana,
With version 3, to submit APK, it always worked well.
With version 4, to submit AAB, it doesn't work.
(I've already tested the AAB submission manually, and it works)

**Comment by VaniaOPereira** [comment] 2021-11-16 17:46
More information; Version : 4.196.0

**Comment by AndreyIvanov42** [comment] 2021-12-29 15:03
@VaniaOPereira 
Could you provide more detailed logs? What command did you use to build your app using bundletool?
I see here many [flags](https://developer.android.com/studio/command-line/bundletool)

**Comment by VaniaOPereira** [comment] 2022-01-12 12:52
I only have this log:
2021-11-16T12:50:55.8547630Z ##[warning]Input apkFile was set, but it will not be used in this action
2021-11-16T12:50:55.9515390Z Authenticated with Google Play and getting new edit
2021-11-16T12:50:57.7063690Z ##[error]Error: Failed to upload the bundle /Users/runner/work/r1/a/TestApp.aab. Failed with message: Error: We have failed to run 'bundletool build-apks' on this Android App Bundle. Please ensure your bundle is valid by running 'bundletool build-apks' locally and try again. Error message output: File 'BundleConfig.pb' was not found..
2021-11-16T12:50:57.7134080Z ##[section]Finishing: Release /Users/runner/work/r1/a/TestApp.aab to internal copy

**Comment by scottbabcock** [comment] 2022-02-22 19:09
I am running into this issue as well. 

These are the only logs I have: 
> 2022-02-22T18:44:16.4060420Z ##[section]Starting: Release to Play Store
2022-02-22T18:44:16.4071630Z ==============================================================================
2022-02-22T18:44:16.4071900Z Task         : Google Play - Release
2022-02-22T18:44:16.4072120Z Description  : Release an app to the Google Play Store
2022-02-22T18:44:16.4072330Z Version      : 4.201.0
2022-02-22T18:44:16.4072510Z Author       : Microsoft Corporation
2022-02-22T18:44:16.4073380Z Help         : ms-resource:loc.helpMarkDown
2022-02-22T18:44:16.4073640Z ==============================================================================
2022-02-22T18:44:17.5526220Z Authenticated with Google Play and getting new edit
2022-02-22T18:44:19.6353140Z ##[error]Error: Failed to upload the bundle /bin/App.apk. Failed with message: Error: We have failed to run 'bundletool build-apks' on this Android App Bundle. Please ensure your bundle is valid by running 'bundletool build-apks' locally and try again. Error message output: File 'BundleConfig.pb' was not found..
2022-02-22T18:44:19.6416000Z ##[section]Finishing: Release to Play Store

**Comment by AndreyIvanov42** [comment] 2022-02-24 14:29
Hi @VaniaOPereira 
Sorry, I missed your message.
Based on your logs, it is hard to determine the cause of the error. Remember that this extension is essentially a [Node.js script](https://github.com/microsoft/google-play-vsts-extension/tree/master/Tasks/GooglePlayReleaseV4).
You can read more about internals [here](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#step-1-create-a-custom-task). In particular, you can run the task [locally](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#run-the-task).

**Comment by AndreyIvanov42** [comment] 2022-03-11 08:57
Try to find the cause of the error. I can't help you using just the information provided. While I close this ticket

**Closed by AndreyIvanov42** 2022-03-11 08:57 UTC
Labels: bug, Area: GooglePlay

**Comment by kjpluck** [comment] 2022-09-21 16:48
Check that you weren't uploading an .apk with action: 'SingleBundle' set.

Make sure it's set to action: 'SingleApk'.

Wasted half a day there.
