### ISSUE TITLE
Can't use release aab with yaml

### ISSUE THREAD

**Issue by praveendath92** [microsoft/google-play-vsts-extension#142] opened 2019-10-23 00:23 UTC
```

##[debug]loading INPUT_METADATAROOTPATH
##[debug]loading INPUT_SHOULDUPLOADMAPPINGFILE
##[debug]loading INPUT_MAPPINGFILEPATH
##[debug]loading INPUT_VERSIONCODEFILTERTYPE
##[debug]loading ENDPOINT_AUTH_7a37d71f-d930-44fb-afea-5ca9e3f7bc82
##[debug]loading ENDPOINT_AUTH_SCHEME_7a37d71f-d930-44fb-afea-5ca9e3f7bc82
##[debug]loading ENDPOINT_AUTH_PARAMETER_7a37d71f-d930-44fb-afea-5ca9e3f7bc82_USERNAME
##[debug]loading ENDPOINT_AUTH_PARAMETER_7a37d71f-d930-44fb-afea-5ca9e3f7bc82_PASSWORD
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loaded 23
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]task result: Failed
##[error]Unhandled: Unexpected identifier
##[debug]Processed: ##vso[task.issue type=error;]Unhandled: Unexpected identifier
##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Unexpected identifier
Finishing: Publish to production on Play Store

```

**Comment by praveendath92** [comment] 2019-10-23 00:25
We are running the task on self hosted agent. Our self hosted agent is based on Ubuntu 16.04

We install node while building our agent this way
```
RUN curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
RUN apt-get update && apt-get -y install nodejs
```

**Comment by praveendath92** [comment] 2019-10-23 00:31
This is how we use the plugin in yaml

```
- task: ms-vsclient.google-play.google-play-release-bundle.GooglePlayReleaseBundle@3
  inputs:
    serviceConnection: ${{ parameters.playStoreServiceConnection }}
    applicationId: ${{ parameters.playStoreApplicationId }}
    bundleFile: ${{ parameters.appBundlePath }}
  displayName: 'Publish to production on Play Store'
```

**Comment by praveendath92** [comment] 2019-10-23 00:48
Tried with different agents from Microsoft pool and with UI.  GooglePlayReleaseBundle (3.160.0) always fails with the same error

**Comment by lassana** [comment] 2019-10-23 07:29
Same problem with our custom agent (Windows based):
`##[error]Unhandled: Unexpected identifier`

**Comment by tinchev** [comment] 2019-10-24 06:59
Same here I get this even without using yaml and on a Azure Hosted Agent

**Comment by praveendath92** [comment] 2019-10-24 08:22
I verified the plugin on Azure Hosted Agents on all 3 platforms. It gives the same error

**Comment by slang25** [comment] 2019-10-24 10:43
Seeing the same thing with non-yaml pipelines too (on macOS):
https://github.com/microsoft/google-play-vsts-extension/pull/138#issuecomment-541753581

**Comment by AgUnityTest** [comment] 2019-10-28 04:01
> Same problem with our custom agent (Windows based):
> `##[error]Unhandled: Unexpected identifier`

Same here

**Comment by cyrilcathala** [comment] 2019-10-30 13:11
Same here, with hosted agent non-yaml pipeline.

**Comment by slang25** [comment] 2019-10-30 13:28
I wonder if it's to do with the version of node it's running under. Maybe the task needs to be `Node10` rather than `Node` which is implicitly version 6.

**Comment by marcostoodoo** [comment] 2019-10-31 15:46
Same here. It´s a generic error, cant figure whats going on

**Comment by Reubenator** [comment] 2019-11-01 20:43
Am seeing the same issue - Google Play - Release Bundle.

Seeing nothing useful in the logs - even when turned up to verbose output, I'm new to this plugin - has it ever worked?

`2019-11-01T20:34:31.7937252Z ==============================================================================
2019-11-01T20:34:31.7937307Z Task         : Google Play - Release Bundle
2019-11-01T20:34:31.7937335Z Description  : Release an app bundle to the Google Play Store
2019-11-01T20:34:31.7937378Z Version      : 3.160.0
2019-11-01T20:34:31.7937404Z Author       : Microsoft Corporation
2019-11-01T20:34:31.7937432Z Help         : ms-resource:loc.helpMarkDown
2019-11-01T20:34:31.7937459Z ==============================================================================
2019-11-01T20:34:32.0218064Z ##[debug]agent.TempDirectory=d:\a\_temp
2019-11-01T20:34:32.0248368Z ##[debug]loading inputs and endpoints
2019-11-01T20:34:32.0254740Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2019-11-01T20:34:32.0267573Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2019-11-01T20:34:32.0271170Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2019-11-01T20:34:32.0273545Z ##[debug]loading INPUT_APPLICATIONID
2019-11-01T20:34:32.0275674Z ##[debug]loading INPUT_AUTHTYPE
2019-11-01T20:34:32.0277333Z ##[debug]loading INPUT_BUNDLEFILE
2019-11-01T20:34:32.0279068Z ##[debug]loading INPUT_CHANGELOGFILE
2019-11-01T20:34:32.0280784Z ##[debug]loading INPUT_LANGUAGECODE
2019-11-01T20:34:32.0282512Z ##[debug]loading INPUT_MAPPINGFILEPATH
2019-11-01T20:34:32.0284435Z ##[debug]loading INPUT_METADATAROOTPATH
2019-11-01T20:34:32.0286128Z ##[debug]loading INPUT_ROLLOUTTOUSERFRACTION
2019-11-01T20:34:32.0287928Z ##[debug]loading INPUT_SERVICEACCOUNTKEY
2019-11-01T20:34:32.0289521Z ##[debug]loading INPUT_SHOULDATTACHMETADATA
2019-11-01T20:34:32.0291166Z ##[debug]loading INPUT_SHOULDUPLOADMAPPINGFILE
2019-11-01T20:34:32.0292653Z ##[debug]loading INPUT_TRACK
2019-11-01T20:34:32.0294816Z ##[debug]loading INPUT_USERFRACTION
2019-11-01T20:34:32.0296295Z ##[debug]loading INPUT_VERSIONCODEFILTERTYPE
2019-11-01T20:34:32.0316480Z ##[debug]loaded 17
2019-11-01T20:34:32.0334342Z ##[debug]Agent.ProxyUrl=undefined
2019-11-01T20:34:32.0336162Z ##[debug]Agent.CAInfo=undefined
2019-11-01T20:34:32.0336784Z ##[debug]Agent.ClientCert=undefined
2019-11-01T20:34:32.0339335Z ##[debug]Agent.SkipCertValidation=undefined
2019-11-01T20:34:32.0569707Z ##[debug]task result: Failed
2019-11-01T20:34:32.0626742Z ##[error]Unhandled: Unexpected identifier`

**Comment by slang25** [comment] 2019-11-01 20:56
I suspect the published artifact has never worked, however this was working while being developed. This is why I'm thinking its node version dependant. But I'm speculating here.

**Comment by rviannaoliveira** [comment] 2019-11-07 20:14
someone have some news?

**Comment by Unity-G** [comment] 2019-11-12 22:11
Has anyone a workaround beside deploying as apk?

**Comment by jooni91** [comment] 2019-11-12 22:33
@Unity-G the one and boring option I am using until this gets fixed is to just download the CI artifact and upload the generated .aab manually to the Google Play store.

**Comment by FanerYedermann** [comment] 2019-11-13 08:10
Same. The workaround is simply to not use it. I just went ahead and wrote my own upload script in the mean-time, using the python libs from Google. Bit more code bloat, but it works.

**Comment by ddfreiling** [comment] 2019-11-13 09:51
@erjohnms Hi, as you merged this, is there any chance you could help debug this? I have no idea how to test the task with an actual Azure build agent while developing. Do you know what the procedure is?

**Comment by 1Siger1** [comment] 2019-11-18 17:28
@FanerYedermann can you share your upload script? 
@erjohnms Can answer something? People here need your help!

**Comment by FanerYedermann** [comment] 2019-11-18 18:06
@1Siger1 Absolutely. I'll post a gist as soon as I get to my computer (probably tomorrow).

**Comment by FanerYedermann** [comment] 2019-11-18 20:25
@1Siger1 https://github.com/FanerYedermann/GooglePlayUpload
I hope I didn't make any copy-paste errors when ripping it out of my build pipe. Let me know if you have any issues.

**Comment by blundell** [comment] 2019-11-19 13:21
![](http://marketingfunnelautomation.com/wp-content/uploads/2016/01/Bump-sign-832x560.jpg)

anyone from Microsoft on this thread? I can't tell if this has even been picked up yet

**Comment by slang25** [comment] 2019-11-19 13:42
Another workaround for now is to use fastlane which ships on the Azure DevOps macOS build agents:
https://github.com/microsoft/google-play-vsts-extension/issues/100#issuecomment-521830135

**Comment by 1Siger1** [comment] 2019-11-19 15:27
@FanerYedermann thank you for the fast answer and the script. For now I am checking the link from @slang25. It looks a lot easier to implement. In case of failure I will try your python approach.

**Comment by andrewleader** [comment] 2019-11-22 03:19
I'm blocked by this issue too :(

**Comment by jeromelaban** [comment] 2019-11-22 03:52
Same thing here. /cc @jamesmontemagno as you've been writing about this lately :)

**Comment by jamesmontemagno** [comment] 2019-11-22 05:37
I ship my apps to App Center first and then connect to Google Play from there. I haven't tested aab files yet though from that end.

**Comment by andrewleader** [comment] 2019-11-22 05:51
The workaround to [use fastlane](https://github.com/microsoft/google-play-vsts-extension/issues/100#issuecomment-521830135) (from Mac agent) was super straightforward and easy! [I documented it a bit more here](https://medium.com/@andrewleader/publish-android-aab-to-google-play-store-using-azure-devops-pipelines-485683f3b9ec).

**Comment by arctouch-carlosottoboni** [comment] 2019-11-25 11:48
@erjohnms Could you please review this PR? It's affecting everyone. It's a simple fix.

**Comment by mayeager22** [comment] 2019-12-17 21:23
This should not be closed...it is not fixed.

**Comment by Praeterii** [comment] 2019-12-18 13:45
We are still getting unexpected identifier error on newest version (3.163.0), so the issue is not fixed.

**Comment by leantk** [comment] 2019-12-18 14:40
This is being looked into still

**Comment by aadesola** [comment] 2019-12-19 10:23
We are experiencing same issue too.

**Comment by erjohnms** [comment] 2019-12-19 17:09
I've merged some fixes of problems I found and published 3.164
Please try it out and let us know how it goes

**Closed** 2019-12-19 20:18 UTC

**Comment by mayeager22** [comment] 2019-12-19 22:21
I can confirm that the task is now working in classic (non-yaml) release pipeline using version 3.164.0.

**Comment by slang25** [comment] 2019-12-23 17:06
Thanks to everyone who worked to get this working 🙂

I have an app bundle in our testing track now!

**Comment by aadesola** [comment] 2019-12-26 16:56
Thanks to everyone that made this work. Our releases are successful now.

2019-12-24T09:03:07.5318712Z Updating track information...
2019-12-24T09:03:36.4636665Z Bundle successfully published!
2019-12-24T09:03:36.4637278Z Track: internal
