### ISSUE TITLE
Error on VSTS task install 

### ISSUE THREAD

**Issue by Woboz** [Microsoft/google-play-vsts-extension#72] opened 2017-07-26 10:35 UTC
Hi

I'm getting "An undefined error occurred while attempting to connect to the server. Status code 0: error." when I try and add to my VSTS.

Any ideas?

Regards

Dave

**Comment by Woboz** [comment] 2017-07-28 13:50
New more helpful message today:

A task definition with id '8CF7CAC0-620B-11E5-B4CF-8565E60F4D27', name '' has already been uploaded. To replace the existing definition, provide a task version which is greater than '1.119.0'.
--

**Comment by rafalmalek** [comment] 2017-08-09 08:15
I've got same problem
![image](https://user-images.githubusercontent.com/16857116/29111706-99ca67ce-7ceb-11e7-908b-c6d20571a529.png)

**Comment by yacaovsnc** [comment] 2017-08-09 18:59
If you go to manage extensions:
https://<youraccount>.visualstudio.com/_admin/_extensions?tab=manage&status=active

Do you see the extension installed?

**Comment by rafalmalek** [comment] 2017-08-10 11:51
No. I only have this:

- Colin's ALM Corner Build & Release Tools by Colin's ALM Corner
- HockeyApp by Microsoft
- Timetracker by 7pace
- XDT Transform by Guillaume Rouchon

**Comment by yacaovsnc** [comment] 2017-08-10 13:27
This error is quite odd, looks like this guid has already been installed on the account.  Is this the first time you tried to install this extension?  

There is a cli tool that can list out all the tasks, would you please try list out the tasks in your account and see if some other tasks share the same guid? 

https://github.com/Microsoft/tfs-cli/blob/master/docs/buildtasks.md#list

**Comment by madhurig** [comment] 2017-12-14 20:33
@Woboz @rafalmalek : Do you still have this issue with installing the extension? Please provide your account name if you are still seeing this issue and we will check if we can fix it.

Thanks,
Madhuri

**Comment by madhurig** [comment] 2018-01-05 13:44
Closing since this is not a bug in the extension and we think has been resolved on the VSTS service. If you continue to have issues, please contact us with your account name and we can resolve it for you. 

Thanks,
Madhuri

**Closed by madhurig** 2018-01-05 13:44 UTC

**Comment by goudarzi** [comment] 2018-05-30 09:45
We are facing the same issue with another extension. Perhaps this is something to be raised with VSTS/TFS team.

**Comment by madhurig** [comment] 2018-05-30 13:37
@goudarzi: Please open a ticket on https://developercommunity.visualstudio.com/spaces/21/index.html to be routed to the right VSTS team with details of which extension and VSTS account you are seeing this in. The issue is not specific to a particular extension but might happen more frequently with extensions that are larger in size. 

Thanks,
Madhuri
