### ISSUE TITLE
Error: Input required: authType

### ISSUE THREAD

**Issue by AntRemo** [microsoft/google-play-vsts-extension#259] opened 2021-04-02 00:31 UTC
Hi!

After updating to 3.185.1 getting error during execution.

Worked properly earlier today on 3.174.0

Is there anyway to revert back to 3.174.0?

![image](https://user-images.githubusercontent.com/700388/113366904-8b4d3580-9328-11eb-864f-1a4102490234.png)

Hopefully it can be resolved soon 🤞
Thanks 🙏

**Comment by AntRemo** [comment] 2021-04-02 01:14
For now I just copied 3.174.0 folder contents into the 3.151.1 folder.

Then updated the version code in the various json files and it works.

**Comment by smardine** [comment] 2021-04-02 09:09
same issue from 3.174 to 3.185.1

**Comment by alexander-smolyakov** [comment] 2021-04-02 09:52
Hey, @AntRemo, @smardine! Could you please re-run the pipeline with the “[Enable system diagnostics](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs)” option enabled and share the following information:
- Azure DevOps / TFS version
- Pipeline agent version
- [Pipeline logs with system diagnostics information](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#view-and-download-logs)
- Agent's [Worker logs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#worker-diagnostic-logs) and [diagnostic logs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#agent-diagnostic-logs)

Also, could you try to set up the new [v2.184.2](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.184.2) agent and see if the problem is still relevant for you? The only thing you need to do is add the environment variable `AZP_AGENT_DOWNGRADE_DISABLED` with `true` value to your pipeline.

Thanks!

**Comment by AntRemo** [comment] 2021-04-02 21:05
@alex-peck I will see if I am allowed to share logs.

In the meantime, I am using v2.131.0 of agent.

TFS Version 16.131.28601.4

**Comment by anatolybolshakov** [comment] 2021-04-05 10:16
@AntRemo thanks! As an option - you can send them to my email so we could investigate it - v-anbols@microsoft.com

**Comment by smardine** [comment] 2021-04-15 08:38
Hello, the same problem exist in the "Promote" task, as a workaround, i found that , in the task folder, i can modify the task.json file

from
`"execution": {
        "Node10": {
            "target": "google-play-promote.js",
            "argumentFormat": ""
        },
        "PowerShell": {
            "target": "$(currentDirectory)\\google-play-promote.ps1",
            "argumentFormat": "",
            "workingDirectory": "$(currentDirectory)"
        }
    },`
to
`"execution": {
        "Node": {
            "target": "google-play-promote.js",
            "argumentFormat": ""
        },
        "PowerShell": {
            "target": "$(currentDirectory)\\google-play-promote.ps1",
            "argumentFormat": "",
            "workingDirectory": "$(currentDirectory)"
        }
    },`
this workaround works for the two task, release and promote.

 - the build agent machine is a windows server  2012 r2
 - the build agent version is 2.136.1
 - the node version installed on this server is 10.15.1
 - The tfs version is 16.131.28106.2 (Tfs2018.Update3) (it's a "OnPermise")
 

I have sended the requested logs to your mail as there is some sensitive info about my company :)

**Comment by anatolybolshakov** [comment] 2021-04-19 13:35
Hi everyone! We are looking into this issue at the moment, as as workaround - you can update agent to the last version, you just need to set 'AZP_AGENT_DOWNGRADE_DISABLED' environment variable to 'true' before update - so there won't be downgrade to current agent version for on-premise solution.

**Comment by max-zaytsev** [comment] 2021-04-23 12:23
Hi @AntRemo, 
This issue related to the old agent version and the old PowerShell execution handler.
We are going to increase the minimum agent version for google play tasks and get rid of outdated  PS handler in the next release. So closing the ticket for now.

**Closed by max-zaytsev** 2021-04-23 12:23 UTC
Labels: Area: ABTT, Task: GPlay Release, bug
