### ISSUE TITLE
"TypeError: the target of promisifyAll must be an object or a function" using Increase Rollout step

### ISSUE THREAD

**Issue by AdamEssenmacher** [Microsoft/google-play-vsts-extension#70] opened 2017-07-05 14:43 UTC
I encounter an error when using the Increase Rollout task.

Step configuration:
![step configuration](https://user-images.githubusercontent.com/8496021/27869560-4c247cc8-616e-11e7-98f9-93dc878bc1fb.PNG)

Error log:

`2017-06-30T21:31:53.7339450Z ##[section]Starting: Increase com.roofsnap.schemingorca rollout fraction to .25
2017-06-30T21:31:53.7469450Z ==============================================================================
2017-06-30T21:31:53.7479450Z Task         : Google Play - Increase Rollout
2017-06-30T21:31:53.7479450Z Description  : Increase the rollout fraction of an app previously deployed to the Google Play Store
2017-06-30T21:31:53.7479450Z Version      : 1.112.0
2017-06-30T21:31:53.7479450Z Author       : Microsoft Corporation
2017-06-30T21:31:53.7479450Z Help         : 
2017-06-30T21:31:53.7479450Z ==============================================================================
2017-06-30T21:31:54.8666817Z c44c8717-c8ae-422d-b9bd-69bce0286783 exists true
2017-06-30T21:31:54.8786825Z ##[error]TypeError: the target of promisifyAll must be an object or a function
2017-06-30T21:31:54.8786825Z 
2017-06-30T21:31:54.8786825Z     See http://goo.gl/9ITlV0
2017-06-30T21:31:54.8786825Z 
2017-06-30T21:31:54.8806819Z 
2017-06-30T21:31:54.8806819Z     See http://goo.gl/9ITlV0
2017-06-30T21:31:54.8806819Z 
2017-06-30T21:31:54.8856827Z ##[section]Finishing: Increase com.roofsnap.schemingorca rollout fraction to .25
`

**Comment by yacaovsnc** [comment] 2017-07-07 13:11
Thanks @AdamEssenmacher for reporting this issue.  Can you please go the **Variables** tab of your build definition and set a variable named **System.Debug** to true?  Then after reproducing the failed build, can you please attach the log here?

Thanks!

**Comment by AdamEssenmacher** [comment] 2017-07-10 16:32
> Can you please go the Variables tab of your build definition and set a variable named System.Debug to true? Then after reproducing the failed build, can you please attach the log here?

I'll do this when we roll out our next version.

**Comment by AdamEssenmacher** [comment] 2017-07-17 14:43
Here it is:

`2017-07-17T14:37:26.3849471Z ##[section]Starting: Increase com.roofsnap.schemingorca rollout fraction to .25
2017-07-17T14:37:26.3989478Z ==============================================================================
2017-07-17T14:37:26.3989478Z Task         : Google Play - Increase Rollout
2017-07-17T14:37:26.3989478Z Description  : Increase the rollout fraction of an app previously deployed to the Google Play Store
2017-07-17T14:37:26.3989478Z Version      : 1.112.0
2017-07-17T14:37:26.3989478Z Author       : Microsoft Corporation
2017-07-17T14:37:26.3989478Z Help         : 
2017-07-17T14:37:26.3989478Z ==============================================================================
2017-07-17T14:37:27.0950030Z ##[debug]agent.workFolder=d:\a
2017-07-17T14:37:27.0950030Z ##[debug]loading inputs and endpoints
2017-07-17T14:37:27.0950030Z ##[debug]loading ENDPOINT_AUTH_00000000-0000-0000-0000-000000286783
2017-07-17T14:37:27.0960028Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_00000000-0000-0000-0000-000000286783_PASSWORD
2017-07-17T14:37:27.0960028Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_00000000-0000-0000-0000-000000286783_USERNAME
2017-07-17T14:37:27.0960028Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2017-07-17T14:37:27.0960028Z ##[debug]loading ENDPOINT_AUTH_SCHEME_00000000-0000-0000-0000-000000286783
2017-07-17T14:37:27.0960028Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2017-07-17T14:37:27.0960028Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2017-07-17T14:37:27.0970026Z ##[debug]loading INPUT_AUTHTYPE
2017-07-17T14:37:27.0970026Z ##[debug]loading INPUT_PACKAGENAME
2017-07-17T14:37:27.0970026Z ##[debug]loading INPUT_SERVICEACCOUNTKEY
2017-07-17T14:37:27.0970026Z ##[debug]loading INPUT_SERVICEENDPOINT
2017-07-17T14:37:27.0970026Z ##[debug]loading INPUT_USERFRACTION
2017-07-17T14:37:27.0970026Z ##[debug]loaded 12
2017-07-17T14:37:27.5190024Z ##[debug]check path : d:\a\_tasks\GooglePlayIncreaseRollout_00000000-0000-0000-0000-000000078153\1.112.0\task.json
2017-07-17T14:37:27.5190024Z ##[debug]set resource file to: d:\a\_tasks\GooglePlayIncreaseRollout_00000000-0000-0000-0000-000000078153\1.112.0\task.json
2017-07-17T14:37:27.5190024Z ##[debug]system.culture=en-US
2017-07-17T14:37:27.5190024Z ##[debug]authType=ServiceEndpoint
2017-07-17T14:37:27.5190024Z ##[debug]serviceEndpoint=00000000-0000-0000-0000-000000286783
2017-07-17T14:37:27.5190024Z 00000000-0000-0000-0000-000000286783 exists true
2017-07-17T14:37:27.5190024Z ##[debug]00000000-0000-0000-0000-000000286783 exists true
2017-07-17T14:37:27.5190024Z ##[debug]packageName=com.roofsnap.schemingorca
2017-07-17T14:37:27.5190024Z ##[debug]userFraction=.25
2017-07-17T14:37:27.5190024Z ##[debug]task result: Failed
2017-07-17T14:37:27.5250036Z ##[error]TypeError: the target of promisifyAll must be an object or a function
2017-07-17T14:37:27.5250036Z ##[debug]Processed: ##vso[task.issue type=error;]TypeError: the target of promisifyAll must be an object or a function
2017-07-17T14:37:27.5250036Z 
2017-07-17T14:37:27.5250036Z     See http://goo.gl/9ITlV0
2017-07-17T14:37:27.5250036Z 
2017-07-17T14:37:27.5270008Z ##[debug]Processed: ##vso[task.complete result=Failed;]TypeError: the target of promisifyAll must be an object or a function
2017-07-17T14:37:27.5270008Z 
2017-07-17T14:37:27.5270008Z     See http://goo.gl/9ITlV0
2017-07-17T14:37:27.5270008Z 
2017-07-17T14:37:27.5290008Z ##[section]Finishing: Increase com.roofsnap.schemingorca rollout fraction to .25`

**Comment by yacaovsnc** [comment] 2017-07-19 14:20
Thanks!  Will take a look very soon.

**Comment by yacaovsnc** [comment] 2017-07-25 20:16
Looking at the log and code, it appears we weren't able to create a JWT client based on the credential provided.  Could you please double check the credentials supplied from the service endpoint?

**Comment by AdamEssenmacher** [comment] 2017-07-26 20:46
The task before this one is a Release to Alpha. It uses the same Authentication Method and Service Endpoint and seems to work fine:
![image](https://user-images.githubusercontent.com/8496021/28642902-f3dd3cde-7221-11e7-88fa-c42e4d71c6d7.png)

**Comment by yacaovsnc** [comment] 2017-07-31 15:02
Hmmm that's interesting.  Could you please attach debug logs from both tasks (in the same run) so we can compare the difference?  This looks like the offending code:  `[[edits, edits.tracks, jwtClient].forEach(Promise.promisifyAll)` , and it is virtually the same in both tasks.  Needs to see why it works in one task but fails in another.  Thanks for your help!

**Comment by AdamEssenmacher** [comment] 2017-07-31 22:36
So, my immediately previous step isn't actually Release to Alpha--that's two steps back. The actual order of my tasks is:

Release to Alpha -> Promote from Alpha to Rollout (10%) ->Increase rollout fraction to 25%

The first two steps work just fine. It's the third step, increasing my rollout fraction to 25%, that errors out.

Each of these steps is in its own VSTS "Environment".

It'll be another week or two before I can get debug logs of these three tasks in the same run.

**Comment by AdamEssenmacher** [comment] 2017-08-23 16:52
Please see the attached logs. Steps 1 and 2 work as expected. Step 3 fails.

[2 - Google Play - Promote.txt](https://github.com/Microsoft/google-play-vsts-extension/files/1246254/2.-.Google.Play.-.Promote.txt)
[3 - Google Play - Increase Rollout.txt](https://github.com/Microsoft/google-play-vsts-extension/files/1246255/3.-.Google.Play.-.Increase.Rollout.txt)
[1 - Google Play - Release.txt](https://github.com/Microsoft/google-play-vsts-extension/files/1246256/1.-.Google.Play.-.Release.txt)

**Comment by yacaovsnc** [comment] 2017-08-23 17:34
Are those three steps from the same build?  It seems there is a 20 hours gap in between step 2 and 3.  

I am asking because the oauth token generated for each build is time sensitive - if they are from the same build, one possibility is this token has expired and the 3rd step weren't able to resolve the credentials from server anymore.  I need to consult with other teams to be sure.

**Comment by yacaovsnc** [comment] 2017-08-23 19:52
aaarrr!  I can't believe I missed such an obvious issue!  Sorry for sending you down the wrong rabbit hole.  It was a problem with jwtClient, but not with the credentials.  

`let jwtClient: any = google.auth.JWT(key.client_email, null, key.private_key, GOOGLE_PLAY_SCOPES, null);` 

This is missing a "new" keyword, it appears the last refactoring introduced this error.

**Comment by AdamEssenmacher** [comment] 2017-08-24 15:53
No problem, I'm just happy the problem has been solved. Thanks for your attention to this!

**Comment by madhurig** [comment] 2017-09-13 16:35
Hi, 

The fix has been released in version 1.123.0 of the extension. Please let us know if you still see an issue.

Thanks,
Madhuri

**Closed by madhurig** 2017-09-13 16:35 UTC
